services:
  mqtt:
    image: eclipse-mosquitto:2.0
    command: mosquitto -c /mosquitto-no-auth.conf
    restart: unless-stopped
    ports:
      - 1883:1883
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:2.7
    restart: unless-stopped
    volumes:
      - /mnt/ssd/docker-configs/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080  # Frontend port
    environment:
      - TZ=America/New_York
      - ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC=zigbee2mqtt
      - ZIGBEE2MQTT_CONFIG_MQTT_SERVER
      - ZIGBEE2MQTT_CONFIG_SERIAL_PORT
      - ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE
      - ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER
      - ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED=false
      - ZIGBEE2MQTT_CONFIG_ADVANCED_TRANSMIT_POWER
      - ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL
      - ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED=true
      - ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED=true
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/ssd/docker-configs/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host