services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "3180:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "3443:443/tcp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - '/mnt/ssd/docker-configs/pihole/etc-pihole:/etc/pihole'
    cap_add:
      - SYS_NICE
    restart: unless-stopped