services:
  pihole:
    container_name: ns01
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "3180:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "3443:443/tcp"
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${FTLCONF_webserver_api_password}
      FTLCONF_dns_listeningMode: 'ALL'
    volumes:
      - '/mnt/ssd/docker-configs/pihole/etc-pihole:/etc/pihole'
    cap_add:
      - SYS_NICE
    restart: unless-stopped

  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    environment:
    - PRIMARY=${PRIMARY}
    - REPLICAS=http://ns01:3180|${FTLCONF_webserver_api_password}
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *
    depends_on:
      pihole:
        condition: service_started